### PR TITLE
Added key, nth, values, members

### PR DESCRIPTION
**Pull request by xgrommx**
Examples will be provided later.

### CODE REVIEW

**Comment by thomashoneyman** [comment]
Thanks! Looking forward to seeing the examples of this in action 👍

**Comment by xgrommx** [comment]
@thomashoneyman this is example (I'll prepare smth for official examples)
https://gist.github.com/xgrommx/1d5127b2c6be78a9c43333f554bb9d5d

**Comment by thomashoneyman** [comment]
@xgrommx Looks good! It'd be fantastic if those could be formulated as tests and added to the test suite as examples.

**Comment by xgrommx** [comment]
@thomashoneyman of course!

**Comment by thomashoneyman** [comment]
@xgrommx just a quick check-in -- still planning on adding those examples / tests? I'd love to make sure these changes are covered and get them merged in.

**Comment by thomashoneyman** [comment]
I'm closing this for inactivity, but please feel free to re-open if you are still interested in getting this merged.

**Pull request closed without merging**
